app = "case-management-be-978"
primary_region = "iad"

[build]

[env]
PORT = "8080"

[http_service]
internal_port = 8080
force_https = true

[[http_service.ports]]
port = 80

[[http_service.ports]]
port = 443
